C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/demo_im.jpg
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/demo_im.jpg
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/demo_im.jpg
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/demo_im.jpg
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils/uploads/demo_im.jpg
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/demo_im.jpg
Exception on / [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 36, in api_root
    iuv = cv2.imread(os.path.join(config['output_dir'],img_name[:-4]+'_IUV.png'))
KeyError: 'output_dir'
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/demo_im.jpg
Exception on / [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 36, in api_root
    iuv = cv2.imread(os.path.join(config['output_dir'],img_name[:-4]+'_IUV.png'))
KeyError: 'output_dir'
C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/
saving C:\Users\MuhammadUsman\PycharmProjects\Texture-Transfer\utils//home/arslanfarooq98/inference_dir/input_imgs/demo_im.jpg
Exception on / [POST]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\ProgramData\Anaconda2\envs\py3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 36, in api_root
    iuv = cv2.imread(os.path.join(config['output_dir'],img_name[:-4]+'_IUV.png'))
KeyError: 'output_dir'
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/4imgs.mp4
Exception on /retreive_texture [POST]
Traceback (most recent call last):
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 57, in retreive_texture
    process_video(saved_path, video_name, flag=1)
  File "main.py", line 45, in process_video
    map_t.extract_texture_from_video(images,iuvs,result_save_file)
  File "/home/arslanfarooq98/Texture-Transfer/utils/texture.py", line 94, in extract_texture_from_video
    self.get_individual_texture(img_frames[i],iuv_frames[i],texture)
  File "/home/arslanfarooq98/Texture-Transfer/utils/texture.py", line 73, in get_individual_texture
    TextureIm[PartInd - 1, mask[0], mask[1], ::-1]+=im[IUV[:, :, 0] == PartInd]*TextureMask
ValueError: operands could not be broadcast together with shapes (0,3) (24,200,200,3,1) 
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/4imgs.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/4imgs.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/4imgs.mp4
Exception on /retreive_texture [POST]
Traceback (most recent call last):
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arslanfarooq98/anaconda3/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "main.py", line 57, in retreive_texture
    process_video(saved_path, video_name, flag=1)
  File "main.py", line 45, in process_video
    map_t.extract_texture_from_video(images,iuvs,result_save_file)
  File "/home/arslanfarooq98/Texture-Transfer/utils/texture.py", line 93, in extract_texture_from_video
    self.get_individual_texture(img_frames[i],iuv_frames[i],texture)
  File "/home/arslanfarooq98/Texture-Transfer/utils/texture.py", line 70, in get_individual_texture
    texture_mask = np.sum(TextureIm[PartInd - 1, mask[0], mask[1], ::-1], axis=-1) == 0
IndexError: index 200 is out of bounds for axis 1 with size 200
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/4imgs.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/IMG_E0115.JPG
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/pic1.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/pic4.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/pic4.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/p6.jpg
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/output.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/output.mp4
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/temp
/home/arslanfarooq98/inference_dir/input_imgs
/home/arslanfarooq98/inference_dir/input_imgs
/home/arslanfarooq98/inference_dir/input_imgs
saving /home/arslanfarooq98/inference_dir/input_imgs/output.mp4
